### ISSUE TITLE
Error: You cannot define a correlation name 'store_table' more than once

### ISSUE THREAD

**Issue by leek** [flagbit/Magento-Faq#6]
Magento 1.8.0.0

```
You cannot define a correlation name 'store_table' more than once

Trace:
#0 lib/Varien/Db/Select.php(281): Zend_Db_Select->_join('inner join', Array, 'main_table.faq_...', Array, NULL)
#1 lib/Zend/Db/Select.php(336): Varien_Db_Select->_join('inner join', Array, 'main_table.faq_...', Array, NULL)
#2 lib/Zend/Db/Select.php(315): Zend_Db_Select->joinInner(Array, 'main_table.faq_...', Array, NULL)
#3 app/code/community/Flagbit/Faq/Model/Mysql4/Faq/Collection.php(89): Zend_Db_Select->join(Array, 'main_table.faq_...', Array)
#4 app/code/community/Flagbit/Faq/Block/Frontend/List.php(77): Flagbit_Faq_Model_Mysql4_Faq_Collection->addStoreFilter(Object(DublinDog_Core_Model_Store))
```

**Comment by bjoern-flagbit** [comment]
PR is merged. Closed.
